config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :links
  resources :views, path: :v, only: :show
  root 'links#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/has_short_code.rb
module HasShortCode
  extend ActiveSupport::Concern

  # Override the to_param use encoded id instead of the default id
  def to_param
    ShortCode.encode(id)
  end

  class_methods do
    # Override the find method to decode the id before finding the record
    def find(id)
      super ShortCode.decode(id)
    end
  end
end

app/models/link.rb
class Link < ApplicationRecord
  include HasShortCode

  belongs_to :user, optional: true
  has_many :views, dependent: :destroy
  validates :url, presence: true

  after_create_commit if: :url_previously_changed? do
    MetadataJob.perform_later(to_param)
  end

  def increment!
    self.views_count += 1
    save!
  end

  def domain
    URI.parse(url).host
  rescue URI::InvalidURIError
    nil
  end

  def editable_by?(user)
    return false if user.blank?

    user.id == user_id
  end
end

app/models/metadata.rb
require 'open-uri'

class Metadata
  attr_reader :doc

  def initialize(html = nil)
    @doc = Nokogiri::HTML(html)
  end

  def self.retrieve_from(url)
    new(URI.open(url))
  rescue StandardError
    nil
  end

  def attributes
    {
      title: title,
      description: description,
      image: image
    }
  end

  def title
    doc.at_css('title')&.text
  end

  def description
    meta_tag_content(property_attribute: 'description')
  end

  def image
    meta_tag_content(name_attribute: :property, property_attribute: 'og:image')
  end

  def meta_tag_content(name_attribute: :name, property_attribute: :property)
    doc.at_css("meta[#{name_attribute}='#{property_attribute}']")&.attributes&.fetch('content', nil)&.text
  end
end

app/models/short_code.rb
class ShortCode
  ALPHABET = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'.freeze
  BASE = ALPHABET.length

  def self.encode(number)
    raise ArgumentError, 'Number must be an integer' unless number.is_a?(Integer)
    raise ArgumentError, 'Number must be positive' if number.negative?

    # Returns `0`
    return ALPHABET[0] if number.zero? || number.nil?

    result = ''
    while number.positive?
      remainder = number % BASE
      character = ALPHABET[remainder]
      result.prepend(character)
      number /= BASE
    end

    result
  end

  def self.decode(string)
    raise ArgumentError, 'Decoded value must be a string' unless string.is_a?(String)

    result = 0
    string.chars.reverse.each_with_index do |character, power|
      character_index = ALPHABET.index(character)
      result += character_index * (BASE**power)
    end

    result
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :lockable, :trackable

  has_many :links, dependent: :destroy
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Method
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update destroy]
  before_action :set_link, only: %i[show edit update destroy]
  before_action :authorized_user, only: %i[edit update destroy]

  def index
    @pagy, @links = pagy(Link.all.includes(:views).order(created_at: :desc))
  end

  def create
    @link = Link.new(link_params.with_defaults(user: current_user))

    if @link.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Link created successfully' }
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.prepend('links', partial: 'links/link', locals: { link: @link }),
            turbo_stream.replace('link_form', partial: 'links/link_form', locals: { link: Link.new })
          ]
        end
      end
    else
      index # runs the code inside the index action, aslong as index does not call render or redirect
      render :index, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @link.update(link_params)
      redirect_to link_path(@link), notice: 'Link updated successfully'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @link.destroy
    redirect_to root_path, notice: 'Link deleted successfully'
  end

  private

  def link_params
    params.require(:link).permit(:url, :title, :description, :image)
  end

  def set_link
    @link = Link.find(params[:id])
  end

  def authorized_user
    redirect_to root_path, alert: 'You are not authorized to edit this link' unless @link.editable_by?(current_user)
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link, only: :show
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def show
    @link.views.create(
      user_agent: request.user_agent,
      ip: request.ip
    )

    redirect_to @link.url, allow_other_host: true
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end

  def record_not_found
    redirect_to root_path, alert: 'Link not found'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favicon_helper.rb
module FaviconHelper
  def favicon_image_tag(domain, **kwargs)
    image_tag google_favicon_url(domain), **kwargs
  end

  def google_favicon_url(domain)
    "https://www.google.com/s2/favicons?domain=#{domain}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://unpkg.com/tippy.js@6"></script>
    <link rel="stylesheet" href="https://unpkg.com/tippy.js@6/animations/scale.css"/>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="mx-auto max-w-[60%]">
      <% if notice %>
        <p class="notice bg-green-100 text-green-800 p-4 rounded-md"><%= notice %></p>
      <% end %>
      
      <% if alert %>
        <p class="alert bg-red-100 text-red-800 p-4 rounded-md"><%= alert %></p>
      <% end %>
    </div>

    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link), class: 'border-b border-gray-200 py-2' do %>
  <%= turbo_stream_from link %>

  <div class="grid grid-cols-8 items-center py-4">
    <div class="col-span-5">
      <%= link_to view_path(link), target: :_blank, data: { turbo: false }, class: "text-blue-600 underline" do %>
        <%= favicon_image_tag link.domain, class: "inline-block m-0" %>
        <%= link.title || link.url %>

        <%= tag.div link.description, class: 'text-xs text-gray-700' %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block w-4 h-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
        </svg>
      <% end %>
    </div>

    <div class="col-span-2 text-center text-xs">
      <%= link_to pluralize(link.views.count, 'view'), link, class: "px-2 py-1.5 rounded bg-gray-100 no-underline" %>
    </div>

    <div class="text-center text-xs">
      <%= button_tag "Copy", class: "font-medium px-2 py-1.5 rounded bg-gray-100 no-underline",
                             data: {
                               controller: "clipboard",
                               clipboard_text: view_url(link)
                            } %>
    </div>
  </div>
<% end %>

app/views/links/_link_form.html.erb
<%= form_with model: link, id: 'link_form' do |form| %>
  <div class="w-full flex justify-between">
    <%= form.url_field :url, autofocus: true, class: 'border border-gray-300 rounded px-4 py-2 flex-grow', placeholder: 'Enter URL', required: true %>
    <%= form.button "Save", class: 'bg-gray-100 rounded px-4 py-2 hover:bg-gray-200' %>
  </div>
<% end %>

app/views/links/edit.html.erb
<div>
  <div>
    <div>Edit link</div>
    <%= link_to 'Back', link_path(@link), class: 'text-blue-500 hover:text-blue-700 underline' %>
  </div>

  <div class="">
    <%= form_with model: @link do |form| %>
      <%= form.url_field :url, autofocus: true, class: 'border border-gray-300 rounded px-4 py-2', placeholder: 'Enter URL', required: true %>
      <%= form.button "Save", class: 'bg-gray-100 rounded px-4 py-2 hover:bg-gray-200' %>
    <% end %>
  </div>
</div>

app/views/links/index.html.erb
<div class="max-w-[60%] mx-auto">
  <div class="flex justify-between items-center mb-5">
    <h1 class="text-2xl font-bold">URL Shortener</h1>

    <div>
      <% if user_signed_in? %>
        <%= link_to 'Profile', edit_user_registration_path, class: 'bg-gray-500 text-white px-4 py-2 rounded-md' %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'bg-red-500 text-white px-4 py-2 rounded-md' %>
      <% else %>
        <%= link_to 'Register', new_user_registration_path, class: 'bg-blue-500 text-white px-4 py-2 rounded-md' %>
        <%= link_to 'Login', new_user_session_path, class: 'bg-blue-100 text-blue-800 px-4 py-2 rounded-md' %>
      <% end %>
    </div>
  </div>

  <%= render partial: 'links/link_form', locals: { link: Link.new } %>

  <div id="links">
    <% @links.each do |link| %>
      <%= render partial: 'links/link', locals: { link: link } %>
    <% end %>

    <%== @pagy.series_nav %>
  </div>
</div>

app/views/links/show.html.erb
<div>
  <%= link_to 'Back', root_path, class: 'text-blue-500 hover:text-blue-700 underline mb-10' %>

  <% if link.editable_by?(current_user) %>
    <%= link_to 'Edit', edit_link_path(@link), class: 'bg-blue-500 text-white px-4 py-2 rounded-md mb-10 block w-fit hover:bg-blue-600' %>
    <%= link_to 'Delete', link_path(@link), class: 'bg-red-500 text-white px-4 py-2 rounded-md mb-10 block w-fit hover:bg-red-600', data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this link?' } %>
  <% end %>

  <%= button_tag "Copy", class: "font-medium px-2 py-1.5 rounded bg-gray-100 no-underline",
                             data: {
                               controller: "clipboard",
                               clipboard_text: view_url(@link)
                            } %>

  <%= render partial: 'links/link', locals: { link: @link } %>
  <h1 class="text-2xl font-bold"><%= @link.title %></h1>
  <p class="text-gray-500 bg-gray-100 p-4 rounded-md my-5">
    <%= @link.description %>
  </p>
  <%= link_to view_path(@link), class: 'text-blue-500 hover:text-blue-700 underline', target: :blank, data: { turbo: false } do %>
    <%= @link.url %>
    <span class="text-gray-500 text-sm"><%= @link.views_count %> views</span>
  <% end %>

  <%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true).count %>
</div>

app/views/views/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Views#show</h1>
  <p>Find me in app/views/views/show.html.erb</p>
</div>